# 侧边栏配置
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post # 页面中高亮的 menu_id
      theme: "#1BCDFC" # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 首页 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: wiki
      theme: "#3DC550"
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: explore
      theme: "#FA6400"
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/sites/收藏的站点.html
    - id: social
      theme: "#F44336"
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /social/friends/

# 站点主结构树
site_tree:
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: welcome, recent # for categories/tags/archives
    rightbar: ghrepos
    nav_tabs: # 近期发布 分类 标签 专栏 归档 and ...
      "新闻": /news/
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: ghissues, related, recent # for wiki
    rightbar: ghrepos
    nav_tabs:
  # 博客文章内页配置
  home:
    leftbar: welcome, TenYearAgreement
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: related, recent # for pages using 'layout:post'
    rightbar: ghrepo, toc
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: tree
    rightbar: ghrepo, toc
  # 错误页配置
  error_page:
    menu_id: post
    "404": "/404.html"
    leftbar: recent
    rightbar: tagcloud, categories
  # 其它自定义页面配置 layout: page
  page:
    leftbar: welcome, TenYearAgreement
    rightbar: timeline

open_graph:
  enable: true
  twitter_id: # for open_graph meta

article:
  type: tech # tech/story: story类文字和段落间增距大。
  auto_cover: false # 根据tags在线搜索封面
  auto_excerpt: 100 # 生成摘要的字
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
  category_color:
    "产品思考": "#4E806F"
    "技术分享": "#4CB9E7"
    "生活思考": "#FF004D"
    "经验分享": "#43766C"
    "设计开发": "#11009E"
  license: "本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。" # 许可协议
  donate:
    wechat: "/assets/images/wepay.jpg"
# 全局样式
style:
  prefers_theme: light
  leftbar:
    background: var(--leftbar-bg)
    blur-px: 100px # 模糊半径
    blur-bg: var(--alpha60) # 模糊颜色
  text-align: left # justify/left/center/right
  darkmode: true # auto true false
  font-size:
    root: 17.5px
    body: 1rem
    code: 80%
    codeblock: 0.8rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
  codeblock:
    highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css
  border-radius:
    card: 12px # 卡片圆角
    block: 12px # 块圆角
    bar: 6px # 导航栏圆角
    image: 6px # 图片圆角

# 页脚
footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/08a41b181ce68.svg"/>'
      url: https://github.com/codepzj
    music:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3845874.svg"/>'
      url: https://music.163.com/#/my/m/music/playlist?id=5469057603
    unsplash:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3616429.svg"/>'
      url: https://share.codepzj.cn/%E4%BA%91%E5%AD%98%E5%82%A8/image
    comments:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/942ebbf1a4b91.svg"/>'
      url: /social/about/#comments
    theme:
      icon: default:theme
      onclick: 'switchTheme()'
  sitemap:
    "博客":
      - "[近期](/)"
      - "[新闻](/news)"
    "项目":
      - "[go学习指南](/wiki/go-learn/入门指南.html)"
      - "[硅谷甄选](/wiki/ggzx/项目起步.html)"
    "站点":
      - "[ChatGPT](https://ai.codepzj.cn/)"
      - "[Gitea](https://repository.codepzj.cn/)"
      - "[Docsify](https://docs.codepzj.cn/)"
    "社交":
      - "[朋友圈](/social/friends/)"
      - "[关于我](/social/about/)"
  content: | # 支持 Markdown 格式
    <img src="/assets/images/keyboard.jpg" alt="描述文字" style="float:right; width:60px; margin-left:20px;">
    <center>
      <div>
        <div>本站点总访问 <span id="busuanzi_value_site_pv" style="font-weight:bold;">2016</span> 次 | 本页访问 <span id="busuanzi_value_page_pv" style="font-weight: bold;">89</span> 次</div>
        <div>
          © 2023 - 2024
          <a style="font-weight: bold;  auto;" target="_blank" rel="noopener" href="https://github.com/codepzj">浩瀚星河</a>
          开心地使用 <a style="font-weight: bold;  auto;" target="_blank" rel="noopener" href="https://github.com/xaoxuu/hexo-theme-stellar">Stellar</a>
          主题，星际地球第<span id="runtime_span"></span>
        </div>
        <a href="https://icp.gov.moe/?keyword=20246646" target="_blank" style="font-weight:bold;">萌ICP备20246646号</a>
        <script async="" src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
        <script type="text/javascript">
          function show_runtime() {
              window.setTimeout("show_runtime()", 1000);
              X = new Date("08/18/2023 00:00:00");
              Y = new Date();
              T = (Y.getTime() - X.getTime());
              M = 24 * 60 * 60 * 1000;
              a = T / M;
              A = Math.floor(a);
              runtime_span.innerHTML = A + "天"
          }
          show_runtime();
        </script>
      </div>
    </center>

copycode:
  enable: true

comments:
  service: twikoo
  twikoo:
    envId: https://twikoo.codepzj.cn # vercel函数
    js: https://gcore.jsdelivr.net/npm/twikoo@1.6.39/dist/twikoo.all.min.js # 建议锁定版本

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: false # 是否搜索代码块（需要content: true)

# 开启图片点击放大功能 {% image %}
tag_plugins:
  image:
    fancybox: true
  icon:
    # 留空时，图标和文字颜色相同
    default_color: accent # theme, accent, red, orange, yellow, green, cyan, blue, purple

# 默认打开
lazyload:
  enable: true # [hexo clean && hexo s] is required after changing this value.
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade

# 默认打开
loading:
  loading: 正在加载
  error: 加载失败，请稍后重试。

inject:
  head:
    - <link rel="stylesheet" href="https://npm.elemecdn.com/lxgw-wenkai-screen-webfont/style.css" media="print" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/code-block.css">
  
  script:
    - <script src="https://cdn.jsdelivr.net/gh/huangwb8/bloghelper@latest/js/input-with-fire.js"></script>
    - <script src="https://cdn.staticfile.org/jquery/3.6.3/jquery.min.js"></script> # jQuery
    - <script src="/js/txmap.js"></script>
    - <script src="/js/snow.js"></script>
    - <script src="/js/code-block.js"></script>

