# 侧边栏配置
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post # 页面中高亮的 menu_id
      theme: "#1BCDFC" # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 首页 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: wiki
      theme: "#3DC550"
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: explore
      theme: "#FA6400"
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/sites/收藏的站点.html
    - id: social
      theme: "#F44336"
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /social/friends/

# 站点主结构树
site_tree:
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: welcome, recent # for categories/tags/archives
    rightbar: ghrepos
    nav_tabs: # 近期发布 分类 标签 专栏 归档 and ...
      "新闻": /news/
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: ghissues, related, recent # for wiki
    rightbar: ghrepos
    nav_tabs:
  # 博客文章内页配置
  home:
    leftbar: welcome, travellings
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: related, recent # for pages using 'layout:post'
    rightbar: ghrepo, toc
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: tree
    rightbar: ghrepo, toc
  # 错误页配置
  error_page:
    menu_id: post
    "404": "/404.html"
    leftbar: recent
    rightbar: tagcloud
  # 其它自定义页面配置 layout: page
  page:
    leftbar: welcome, travellings
    rightbar: timeline

open_graph:
  enable: true
  twitter_id: # for open_graph meta

article:
  type: tech # tech/story: story类文字和段落间增距大。
  auto_cover: false # 根据tags在线搜索封面
  auto_excerpt: false # 生成摘要的字
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
  category_color:
    "产品思考": "#4E806F"
    "技术分享": "#4CB9E7"
    "生活思考": "#FF004D"
    "经验分享": "#43766C"
    "设计开发": "#11009E"
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  share: [wechat, weibo, email, link]
# 全局样式
style:
  prefers_theme: light
  leftbar:
    background: var(--leftbar-bg)
    blur-px: 100px # 模糊半径
    blur-bg: var(--alpha60) # 模糊颜色
  text-align: left # justify/left/center/right
  darkmode: true # auto true false
  font-size:
    root: 17.5px
    body: 1rem
    code: 80%
    codeblock: 0.8rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
  codeblock:
    highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css
  border-radius:
    card: 12px # 卡片圆角
    block: 12px # 块圆角
    bar: 6px # 导航栏圆角
    image: 6px # 图片圆角

# 页脚
footer:
  social:
    github:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="#000000" d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33s1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2"/></svg>'
      url: https://github.com/codepzj
    comment:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><g fill="none" stroke="#000000" stroke-linejoin="round"><path stroke-linecap="round" stroke-width="1.5" d="M12 21a9 9 0 1 0-8-4.873L3 21l4.873-1c1.236.639 2.64 1 4.127 1"/><path stroke-width="2.25" d="M7.5 12h.01v.01H7.5zm4.5 0h.01v.01H12zm4.5 0h.01v.01h-.01z"/></g></svg>'
      url: /social/about/#comments
    mail:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="1.1em" height="1.1em" viewBox="0 0 32 32"><path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2 26h28V6H2ZM2 6l14 10L30 6"/></svg>'
      url: mailto:email@codepzj.cn
    rss:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M4 11a9 9 0 0 1 9 9M4 4a16 16 0 0 1 16 16"/><circle cx="5" cy="19" r="1"/></g></svg>'
      url: /atom.xml
    Moon:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 256 256"><path fill="#000000" d="M233.54 142.23a8 8 0 0 0-8-2a88.08 88.08 0 0 1-109.8-109.8a8 8 0 0 0-10-10a104.84 104.84 0 0 0-52.91 37A104 104 0 0 0 136 224a103.1 103.1 0 0 0 62.52-20.88a104.84 104.84 0 0 0 37-52.91a8 8 0 0 0-1.98-7.98m-44.64 48.11A88 88 0 0 1 65.66 67.11a89 89 0 0 1 31.4-26A106 106 0 0 0 96 56a104.11 104.11 0 0 0 104 104a106 106 0 0 0 14.92-1.06a89 89 0 0 1-26.02 31.4"/></svg>'
      url: javaScript:switchTheme();
  sitemap:
    "博客":
      - "[隐私政策](/document/policy/)"
      - "[免责声明](/document/disclaimer/)"
      - "[网站统计](https://umami.codepzj.cn/share/JA1hZArBwpHuOtAp/blog.codepzj.cn)"
      - "[服务状态](https://status.codepzj.cn/status/codepzj)"
    "项目":
      - "[go学习指南](/wiki/go-learn/入门指南.html)"
      - "[硅谷甄选](/wiki/ggzx/项目起步.html)"
    "探索":
      - "[我的站点](/explore/sites/收藏的站点.html)"
      - "[年度计划](/explore/notes/探索者笔记.html)"
    "社交":
      - "[友链](/social/friends/)"
      - "[说说](/social/talks/)"
      - "[关于](/social/about/)"
  content: | # 支持 Markdown 格式
    <img src="/assets/images/keyboard.jpg" alt="描述文字" style="float:right; width:60px; margin-left:20px;">
    <center>
      
      <script src="https://cdn.jsdelivr.net/npm/qexo-static@1.6.0/hexo/statistic.js"></script>
      <script>
          loadStatistic("https://qexo.codepzj.cn")
      </script>
      <div>
        <div>
          站点访问量:<span id="qexo-site-pv"><span class="load-time"><img src="/assets/images/loading.svg" alt="loading"></span></span>次&nbsp;|&nbsp;站点访客数:<span id="qexo-site-uv"><span class="load-time"><img src="/assets/images/loading.svg" alt="loading"></span></span>次&nbsp;|&nbsp;页面访问量:<span id="qexo-page-pv"><span class="load-time"><img src="/assets/images/loading.svg" alt="loading"></span></span>次&nbsp;|&nbsp;页面载入时间:<span class="load-time"><img src="/assets/images/loading.svg" alt="loading"></span>秒
        </div>
        <div>
          © 2024
          <a style="font-weight: bold;  auto;" target="_blank" rel="noopener" href="https://github.com/codepzj">浩瀚星河</a>
          开心地使用 <a style="font-weight: bold;" target="_blank" rel="noopener" href="https://github.com/xaoxuu/hexo-theme-stellar">Stellar</a>
          主题，星际地球第<span id="runtime_span"></span>
        </div>
        <a href="https://beian.miit.gov.cn/" target="_blank" style="font-weight:bold;">粤ICP备2024275864号</a>
        <script async="" src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
        <script type="text/javascript">
          function show_runtime() {
              window.setTimeout("show_runtime()", 1000);
              X = new Date("08/10/2024 00:00:00");
              Y = new Date();
              T = (Y.getTime() - X.getTime());
              M = 24 * 60 * 60 * 1000;
              a = T / M;
              A = Math.floor(a);
              runtime_span.innerHTML = A + "天"
          }
          show_runtime();
        </script>
      </div>
    </center>

copycode:
  enable: true

comments:
  service: twikoo
  twikoo:
    envId: https://twikoo.codepzj.cn # vercel函数
    js: https://gcore.jsdelivr.net/npm/twikoo@1.6.39/dist/twikoo.all.min.js # 建议锁定版本

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: false # 是否搜索代码块（需要content: true)

# 开启图片点击放大功能 {% image %}
tag_plugins:
  image:
    fancybox: true
  icon:
    # 留空时，图标和文字颜色相同
    default_color: accent # theme, accent, red, orange, yellow, green, cyan, blue, purple

# 默认打开
lazyload:
  enable: true # [hexo clean && hexo s] is required after changing this value.
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade

# 默认打开
loading:
  loading: 正在加载
  error: 加载失败，请稍后重试。

inject:
  head:
    - <link rel="stylesheet" href="https://npm.elemecdn.com/lxgw-wenkai-screen-webfont/style.css" media="print" onload="this.media='all'">
    - <link rel="stylesheet" href="https://unpkg.com/qexo-friends/friends.css"/>
    - <link rel="stylesheet" href="https://gcore.jsdelivr.net/gh/MSCMDD/Qexo-Talks@main/Stellar/qexo_talk.css">
    - <link rel="stylesheet" href="/css/code-block.css">
    - <link rel="stylesheet" href="/css/custom.css">


  script:
    - <script src="https://cdn.jsdelivr.net/gh/huangwb8/bloghelper@latest/js/input-with-fire.js"></script>
    - <script defer src="https://umami.codepzj.cn/script.js" data-website-id="e6fdc7c7-3ad4-446e-9606-135abe5cc035"></script>
    - <script src="/js/code-block.js"></script>
    - <script src="/js/load.js"></script>

