# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 浩瀚星河
icon: /assets/images/avatar.jpg
subtitle: "A Go Enthusiast | 实习前的些许风霜罢了"
avatar: /assets/images/avatar.jpg
author: codepzj
email: email@codepzj.cn
description: "技术,生活,算法"
keywords: "hexo-theme-stellar,刷题,项目,开源,程序猿,产品思考,技术分享,生活思考,经验分享,设计开发"
favicon: /favicon.ico
# subtitle: # subtitle 已移至主题配置中
# 多语言
language:
  - zh-CN
  - en
timezone: "Asia/ShangHai"

logo:
  subtitle: "A Go Enthusiast | 实习前的些许风霜罢了" # 副标题

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.codepzj.cn
permalink: posts/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace: "  "
  wrap: true
  hljs: true
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:codepzj/codepzj.github.io.git
    branch: gh-pages

wiki_dir: wiki

sitemap:
  path: sitemap.xml

# 开启压缩
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - "**/*.min.css"
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "**/*.min.js"
    - "**/index.js"

nofollow:
  enable: true  #true/false 启用/关闭插件
  field: site   #site/post  处理全站/仅文章链接
  exclude:      #排除域名，同的子域名视为不同的域名
    - 'codepzj.cn'
    - 'image.codepzj.cn'
    - 'share.codepzj.cn'
    - 'repository.codepzj.cn'
    - 'memos.codepzj.cn'
    - 'link.codepzj.cn'
    - 'status.codepzj.cn'
    - 'umami.codepzj.cn'
    - 'ai.codepzj.cn'
    - 'oracle.codepzj.cn'
    - 'tools.codepzj.cn'
    - 'docs.codepzj.cn'
    - 'twikoo.codepzj.cn'
    - 'cloud.codepzj.cn'
    - 'admin.codepzj.cn'
    
# auto-push-urls-to-search-engine
hexo_submit_urls_to_search_engine:
  submit_condition: count #链接被提交的条件，可选值：count | period 现仅支持count
  count: 100 # 提交最新的链接个数
  period: 1000 # 提交修改时间在 1000 秒内的链接
  google: 1 # 是否向Google提交（0：否；1：是）
  bing: 1 # 是否向bing提交（0：否；1：是）
  baidu: 1 # 是否向baidu提交（0：否；1：是）
  txt_path: submit_urls.txt ## 文本文档名， 需要推送的链接会保存在此文本文档里
  baidu_host: https://blog.codepzj.cn ## 在百度站长平台中注册的域名
  baidu_token: Z7pgyZfCLvEkPJE5  ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  bing_host: https://blog.codepzj.cn ## 在bing站长平台中注册的域名
  bing_token: f8fd7eea822b45ca844d0182b8e20f73  ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  google_host: https://blog.codepzj.cn ## 在google站长平台中注册的域名
  google_proxy: 0 # 向谷歌提交网址所使用的系统 http 代理，填 0 不使用，以Clash为例
  google_key_file: codepzj-0e4855b9a77c.json #Google服务项目的json文件名全称，放于网站根目录（与hexo _config.yml文件位置相同），请不要把json文件内容直接发布在公众仓库里!
  replace: 0  # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what: 
  replace_with:
