name: Generate atom.xml
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g npm-check-updates

      - name: Cache Modules
        uses: actions/cache@v1
        id: cache-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Generate
        run: |
          hexo clean
          hexo g

      - name: Upload atom.xml as artifact
        uses: actions/upload-artifact@v3
        with:
          name: atom-xml
          path: public/atom.xml

      - name: Deploy atom.xml to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # 部署 public 目录下的文件
          keep_files: true       # 保留已有文件，只更新 atom.xml
          publish_branch: output # 推送到 output 分支
