name: deploy-hexo-blog
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 确保子模块被检出
      # 更新子模块
      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          # 设置远程仓库的 URL，使用 GITHUB_TOKEN 进行身份验证
          git remote set-url origin https://github.com/codepzj/blog.git
          
          # 提交更新并推送
          git commit -am "Auto updated submodule references" && git push origin HEAD || echo "No changes to commit"

      # 安装nodejs
      - name: install nodejs
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "20.12.0"
      # 使用pnpm包管理
      - name: use pnpm
        run: npm i -g pnpm && pnpm config set registry https://registry.npmmirror.com
      # 安装依赖
      - name: install packages
        run: pnpm install
      # 清空缓存
      - name: clear
        run: pnpm run clean
      # 打包项目
      - name: build
        run: pnpm run build
      # 文件复制到服务器 
      - name: copy dist file with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PZJ_HOST }}
          username: ${{ secrets.PZJ_USERNAME }}
          password: ${{ secrets.PZJ_PASSWORD }}
          port: ${{ secrets.PZJ_PORT }}
          source: "public/"
          target: ${{ secrets.PZJ_TARGET }}
      # 使用gh-pages的action提交seo收录
      - name: seo auto submit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          # 确保在正确的目录中
          cd public  # 假设构建输出在 public 目录中
          
          # 初始化一个新的 Git 仓库
          git init
          git add -A
          git commit -m "seo auto submit"

          # 设置远程仓库并推送到 gh-pages 分支
          git remote add origin https://github.com/codepzj/blog.git
          git branch -M gh-pages
          git push -f origin gh-pages